mate-desktop/mate-notification-daemon

src/daemon/daemon.c
backport of https://github.com/mate-desktop/mate-notification-daemon/pull/43 to 1.8 branch
=> [1.8] daemon: fixed logic in a couple of places

src/capplet/mate-notification-properties.c, src/daemon/daemon.c, src/daemon/engines.c
fixes the issue with GLib >= 2.43,
https://git.gnome.org/browse/glib/commit/?id=8ff5668a458344da22d30491e3ce726d861b3619
=> [1.8] first connect to settings, then read them.

src/daemon/daemon.c
Fixes #56. Refer to it for more information.
=> daemon: exit with 0 on idle

src/daemon/daemon.c, src/themes/coco/coco-theme.c, src/themes/nodoka/nodoka-theme.c, src/themes/slider/theme.c, src/themes/standard/theme.c
taken and adjusted from notification-daemon upstream
=> GTK3: fix some deprecations

data/mate-notification-daemon.convert, data/org.mate.NotificationDaemon.gschema.xml.in.in, src/daemon/daemon.h
fixes https://github.com/mate-desktop/mate-notification-daemon/issues/48
=> removed unused "default-sound" key

src/daemon/daemon.c
Just simple three changes I've made while reviewing the code.
=> A bunch of small misc patches

src/themes/slider/theme.c, src/themes/standard/theme.c
Note, slider commit does not fix missing pie.
You can enable the pie with replacing line https://github.com/mate-desktop/mate-notification-daemon/blob/dev-standard/src/themes/slider/theme.c#L704
with
if (gtk_widget_get_visible(windata->actions_box))
...but this is not what i want.
=> GtkStyleContext improvements

src/themes/coco/coco-theme.c, src/themes/nodoka/nodoka-theme.c, src/themes/slider/theme.c, src/themes/standard/theme.c
All themes tested, everything works fine now with all possible situations.
=> Fix: properly escape text

src/daemon/daemon.c
=> Fix memory leak with opera notifications

src/daemon/daemon.c, src/daemon/stack.c, src/daemon/stack.h, src/themes/standard/theme.c
avoid deprecated:
gdk_screen_get_monitor_geometry
gdk_screen_get_monitor_at_point
=> gtk 3.22: avoid deprecated gdk_screen_get_monitor... functions:

configure.ac, src/capplet/mate-notification-properties.c, src/daemon/daemon.c, src/daemon/stack.c, src/daemon/stack.h, src/themes/coco/coco-theme.c, src/themes/nodoka/nodoka-theme.c, src/themes/slider/theme.c, src/themes/standard/theme.c
and drop additional checks for min/max GLib versions, it's not needed
=> require GTK+ 3.22 and GLib 2.50

src/daemon/daemon.c
Please review and test, thank you.
=> Fix some gdk deprecations

configure.ac, src/daemon/Makefile.am, src/daemon/daemon.c, src/daemon/daemon.h, src/daemon/engines.c, src/daemon/engines.h, src/daemon/mnd-daemon.c, src/daemon/notificationdaemon.xml, src/themes/coco/coco-theme.c, src/themes/nodoka/nodoka-theme.c, src/themes/slider/theme.c, src/themes/standard/theme.c
Please review and test, thank you.
=> Migrate from dbus-glib to GDBus

src/daemon/daemon.c, src/daemon/daemon.h
- src/daemon/daemon.c
- src/daemon/daemon.h
=> Avoid compile warning for g_type_class_add_private

.travis.yml
Please review and see the build log.
=> update to use archlinux/base image

configure.ac, src/capplet/mate-notification-properties.c, src/daemon/mnd-daemon.c, src/themes/coco/coco-theme.c, src/themes/nodoka/nodoka-theme.c
`find . -regextype posix-extended -regex '.*\.(c|h|ac)' -exec sed --in-place 's/[[:space:]]\+$//' {} \+`
like rbuj do on [https://github.com/mate-desktop/mate-control-center/pull/463](https://github.com/mate-desktop/mate-control-center/pull/463).
=> Remove trailing whitespaces

src/daemon/daemon.c, src/themes/coco/coco-theme.c, src/themes/nodoka/nodoka-theme.c, src/themes/slider/theme.c, src/themes/standard/theme.c
This is a cherry-pick of #157 to the 1.22 branch.
=> Fix decoding the hints dictionary.

src/daemon/daemon.c
Test (timeout of 7s):
```
$ notify-send -i mate-desktop -t 7000 "hello" "world"
```
=> daemon: Remove warning about GTimeVal deprecation

.build.yml, configure.ac, src/themes/coco/coco-theme.c, src/themes/nodoka/nodoka-theme.c, src/themes/slider/theme.c, src/themes/standard/Makefile.am, src/themes/standard/theme.c
Tests:
```
$ notify-send "title" "<a href=\"https://mate-desktop.org/es/\">MATE</a> <i>italic</i> <b>bold</b>"
$ notify-send "title" "<a href=\"https://mate-desktop.org/es/\">MATE</a> <i>italic</i> <b>bold</b> <qwert>asdf</qwert>"
$ notify-send "title" "<i>italic</i> <b>bold</b>"
```
Closes #118
=> The body of a notification may also contain hyperlinks

src/capplet/mate-notification-applet.c
Also render as scaled cairo surface to support HiDPI displays.
=> applet: Resize icon size with panel

src/capplet/mate-notification-properties.c, src/daemon/engines.c
=> mate-notification-properties: fix memory leaks
