mate-desktop/mate-notification-daemon

- src/themes/coco/coco-theme.c
- src/themes/nodoka/nodoka-theme.c
- src/themes/slider/theme.c
- src/themes/standard/theme.c
fixes https://github.com/mate-desktop/mate-notification-daemon/issues/55
the code used is similar to https://github.com/GNOME/notification-daemon/blob/master/src/nd-bubble.c#L812
@NiceandGently @infirit @flexiondotorg @samtygier
please test for any possible regressions :smile:
> all themes: don't crash on notifications from Rhythmbox

- src/themes/coco/coco-theme.c
- src/themes/nodoka/nodoka-theme.c
- src/themes/slider/theme.c
- src/themes/standard/theme.c
Fix missing prototype warnings in themes. You could just disable -Wmissing-prototypes but it could provide useful information and find potential bugs so it remains and these patches just add the needed prototypes.
> Fix missing prototype warnings in themes

- src/daemon/daemon.c
inspired from:
https://git.gnome.org/browse/notification-daemon/patch/?id=9f376d3
> GTK3 daemon: fix deprecated gdk_display_get_pointer

- src/themes/slider/theme.c
It's enough to call gtk_widget_override_* functions on the toplevel element, child elements will inherit the style properly. Fixes issue #90.
> GTK3 slider: don't call override_style multiple times

- configure.ac
- src/daemon/daemon.c
- src/daemon/stack.c
- src/themes/coco/coco-theme.c
- src/themes/nodoka/nodoka-theme.c
- src/themes/slider/theme.c
- src/themes/standard/theme.c
@flexiondotorg @clefebvre @raveit65 @posophe @XRevan86 @willysr @obache @NP-Hardass
And now we move m-n-d to GTK+3:
- minimum GTK+ version is set to 3.14
- GTK+2 code and deprecated GTK+3 code are dropped
- ```--with-gtk``` build option is dropped as well
- build-deps on GTK+, wnck and canberra dev packages are changed (that's what you need to do in your distros)
For example, in Debian/Ubuntu build-deps are changed as follows:
```libcanberra-gtk-dev -> libcanberra-gtk3-dev```
```libgtk2.0-dev -> libgtk-3-dev```
```libwnck-dev -> libwnck-3-dev```
Also please note that slider theme doesn't use reversed colors from GTK+ theme anymore. It uses your fg/bg as is. I understand it might be a surprise for some users, but we couldn't manage to get the color reversing to work with all GTK+ 3.xx …
> require GTK+ >= 3.14, drop GTK+2 code and --with-gtk build option

- src/daemon/daemon.c
- src/themes/coco/coco-theme.c
- src/themes/nodoka/nodoka-theme.c
- src/themes/slider/theme.c
- src/themes/standard/theme.c
This PR adds support to MATE Notification Daemon for the `action-icons` attribute, per capabilites + hints in the freedesktop Notifications Specification. These permit icons to be used in place of labels, with self describing icons (see 7aeebb6 in this PR for a full explanation)
It also exposed a number of bugs, subsequently fixed, in the existing themes when updating a live notification. The existing textual actions would disappear (`gtk+-3.0 3.20`) once a live notification is updated, for example by Rhythmbox. 
It also turns out that pie_countdown's were duplicated or borky in one respect or another.
As this now returns functionality which has been missing for a while, it also exposed `Coco` buttons being quite ugly, and the pie_countdown in `Slider` having a black background. I feel …
> Implement Action icons Support

- src/daemon/stack.c
- src/themes/nodoka/nodoka-theme.c
This commit reverts:
https://github.com/mate-desktop/mate-notification-daemon/commit/52b7c3807e71278f2d902a79cf6c08c839a1b0ad
And it applies an alternative to fix the deprecated functions:
gdk_screen_get_width
gdk_screen_get_height
> WidthOfScreen and HeightOfScreen implementation

- data/org.mate.NotificationDaemon.gschema.xml.in
- src/capplet/mate-notification-properties.c
- src/capplet/mate-notification-properties.ui
- src/daemon/daemon.c
- src/daemon/daemon.h
Adds a do-not-disturb gsettings boolean key, an "Enable Do Not Disturb" checkbox to mate-notification-properties, and silently discards notifications when the key is set by generating a new return_id and immediately closing the notification.
> Add do-not-disturb setting

- src/daemon/daemon.c
- src/themes/coco/coco-theme.c
- src/themes/nodoka/nodoka-theme.c
- src/themes/slider/theme.c
- src/themes/standard/theme.c
mate-notification-daemon uses g_variant_lookup with a format string of "v" to look up everything in the hints dictionary. That only works if the actual value is a GVariant, but it won't decode strings, integers, etc.
This fixes the g_variant_lookup calls to use the correct type strings. In most cases, it'll also now unpack the values directly instead of fetching them in another GVariant.
> Fix decoding the hints dictionary

- configure.ac
> [1.22] build: drop MATE_CXX_WARNINGS

- src/daemon/daemon.c
- src/daemon/engines.c
- src/daemon/stack.c
- src/themes/coco/coco-theme.c
- src/themes/nodoka/nodoka-theme.c
- src/themes/slider/theme.c
- src/themes/standard/theme.c
```
$ CFLAGS="-Wconversion" ./autogen.sh  --enable-compile-warnings=maximum --prefix=/usr && make &> make.log && sudo make install
$ grep -A 2 conversion make.log
daemon.c:939:24: warning: conversion to ‘gsize’ {aka ‘long unsigned int’} from ‘int’ may change the sign of the result [-Wsign-conversion]
939 |         expected_len = (height - 1) * rowstride + width
|                        ^
daemon.c:951:37: warning: conversion from ‘gsize’ {aka ‘long unsigned int’} to ‘guint’ {aka ‘unsigned int’} may change value [-Wconversion]
951 |                                     g_variant_get_size (data_variant));
|                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--
daemon.c:1036:23: warning: conversion from ‘int’ to ‘float’ may change value [-Wconversion]
1036 |   scale_x = …
```
> Remove conversion warnings

- configure.ac
- src/capplet/mate-notification-properties.c
- src/daemon/Makefile.am
- src/daemon/daemon.c
- src/daemon/engines.c
- src/daemon/mnd-daemon.c
- src/daemon/stack.c
- src/daemon/wayland.c
- src/daemon/wayland.h
- src/themes/nodoka/nodoka-theme.c
- src/themes/standard/Makefile.am
Adds `--enable-x11`/`--enable-wayland` options. Like with the panel you can use the configure options to force enable or disable each backend, or not specify them let the build system detect if the required libraries are present. Wayland support requires [GTK Layer Shell](https://github.com/wmww/gtk-layer-shell). I inserted Wayland code and made X11 code optional with minimal additional refactoring, so it's all a bit rough.
What works:
- Notifications appear
- Notifications are correctly placed (at least in the cases I've seen)
What doesn't:
- Suppressing notifications when there is a full screen window—there isn't an obvious way to do that on stock Wayland.
- Selecting the monitor for notifications to appear on—this should be possible, but I haven't implemented it
> Wayland support

- src/daemon/Makefile.am
```
$ ./autogen.sh --prefix=/usr && make && make distcheck
<cut>
../../../../src/daemon/engines.c:31:10: fatal error: wayland.h: El fitxer o directori no existeix
31 | #include "wayland.h"
|          ^~~~~~~~~~~
compilation terminated.
make[4]: *** [Makefile:549: mate_notification_daemon-engines.o] Error 1
make[4]: Leaving directory '/home/robert/mate-notification-daemon/mate-notification-daemon-1.25.0/_build/sub/src/daemon'
make[3]: *** [Makefile:402: all-recursive] Error 1
make[3]: Leaving directory '/home/robert/mate-notification-daemon/mate-notification-daemon-1.25.0/_build/sub/src'
make[2]: *** [Makefile:484: all-recursive] Error 1
make[2]: Leaving directory '/home/robert/mate-notification-daemon/mate-notification-daemon-1.25.0/_build/sub'
make[1]: *** [Makefile:416: all] Error 2 …
```
> build: Fix make distcheck

- src/capplet/mate-notification-applet.c
> mate-notification-applet: avoid segfault after removing the applet

- src/daemon/daemon.c
NotifyStack is not a GObject, so calling g_clear_object is bad. Interestingly, it caused an endless loop in `g_object_unref()` on my system due to a quark in how the ref count is checked.
> Don't use g_clear_object() on NotifyStack (which is not a GObject)

- src/capplet/mate-notification-properties.c
- src/daemon/daemon.c
```
daemon.c:1528:8: warning: declaration of ‘x’ shadows a previous local [-Wshadow]
1528 |   gint x, y;
|        ^
--
daemon.c:1528:11: warning: declaration of ‘y’ shadows a previous local [-Wshadow]
1528 |   gint x, y;
|           ^
--
daemon.c:1607:24: warning: declaration of ‘data’ shadows a previous local [-Wshadow]
1607 |   _NotifyPendingClose* data;
|                        ^~~~
--
mate-notification-properties.c:83:10: warning: declaration of ‘key’ shadows a parameter [-Wshadow]
83 |   gchar* key;
|          ^~~
```
> Remove shadow warnings [-Wshadow]

- src/daemon/daemon.c
```
daemon.c: In function ‘_store_notification’:
daemon.c:912:9: warning: ‘g_memdup’ is deprecated: Use 'g_memdup2' instead [-Wdeprecated-declarations]
912 |         g_hash_table_insert(daemon->notification_hash, g_memdup(&id, sizeof(guint)), nt);
|         ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:82,
from /usr/include/glib-2.0/glib/gi18n.h:21,
from daemon.c:31:
/usr/include/glib-2.0/glib/gstrfuncs.h:257:23: note: declared here
257 | gpointer              g_memdup         (gconstpointer mem,
|                       ^~~~~~~~
daemon.c: In function ‘_notify_daemon_pixbuf_from_data_hint’:
daemon.c:953:9: warning: ‘g_memdup’ is deprecated: Use 'g_memdup2' instead [-Wdeprecated-declarations]
953 |         data = (guchar *) g_memdup (g_variant_get_data …
```
> daemon: g_memdup is dreprecated from glib 2.68

- data/org.freedesktop.mate.Notifications.service.in
Snap packages are unable to trigger the notification daemon in a fully confined package, because the snapd apparmor rules state that the target of the dbus call must specify that it is labelled `unconfined`. See https://forum.snapcraft.io/t/snapd-doesnt-allow-notification-daemon-to-be-activatable/22912/1 for the details.
* Add `AssumedAppArmorLabel` rule to dbus service file
> Add AssumedAppArmorLabel to dbus service file

- src/themes/standard/theme.c
Test
```
grep -R -w "^[[:space:]]*#if\|^[[:space:]]*#else\|[[:space:]]*#endif\|[[:space:]]*#ifdef\|#define" --include *.c | grep -F ": "
```
> theme: remove whitespaces before #define, #ifdef, and #endif

- src/daemon/daemon.c
```
==1968==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 20 byte(s) in 1 object(s) allocated from:
#0 0x7f0a4cb9793f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7f0a4babeb7f in g_malloc ../glib/gmem.c:106
#2 0x7f0a4babeec2 in g_malloc_n ../glib/gmem.c:344
#3 0x7f0a4bae11a5 in g_strdup ../glib/gstrfuncs.c:364
#4 0x413d71 in notify_daemon_get_server_information /home/robert/builddir.gcc/mate-notification-daemon/src/daemon/daemon.c:1688
#5 0x7f0a4ad0ac03 in ffi_call_unix64 (/lib64/libffi.so.6+0x6c03)
#6 0x7ffd4a2af5af  ([stack]+0x1f5af)
Direct leak of 7 byte(s) in 1 object(s) allocated from:
#0 0x7f0a4cb9793f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7f0a4babeb7f in g_malloc ../glib/gmem.c:106
#2 0x7f0a4babeec2 in g_malloc_n ../glib/gmem.c:344
#3 …
```
> daemon: fix memory leak

- src/daemon/mnd-daemon.c
```
CC=gcc CFLAGS="-ggdb3 -O0 -fsanitize=address" LDFLAGS="-fsanitize=address"  ./autogen.sh --prefix=/usr --enable-debug  --enable-compile-warnings=maximum && make &> make.log && sudo make install
```
```
LeakSanitizer: detected memory leaks
Direct leak of 88 byte(s) in 1 object(s) allocated from:
#0 0x7fd1deb6baf7 in calloc (/lib64/libasan.so.6+0xaeaf7)
#1 0x7fd1dda92c04 in g_malloc0 ../glib/gmem.c:136
#2 0x7fd1dda92f52 in g_malloc0_n ../glib/gmem.c:368
#3 0x7fd1dda99c4a in g_option_context_new ../glib/goption.c:365
#4 0x417ce2 in parse_arguments /home/robert/builddir.gcc/mate-notification-daemon/src/daemon/mnd-daemon.c:59
#5 0x417f17 in main /home/robert/builddir.gcc/mate-notification-daemon/src/daemon/mnd-daemon.c:92
#6 0x7fd1dd70ab74 in __libc_start_main (/lib64/libc.so.6+0x27b74) …
```
> mnd-daemon: fix memory leak

- src/capplet/mate-notification-properties.c
- src/daemon/mnd-daemon.c
```
mnd-daemon.c:51:2: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
}
^
--
mate-notification-properties.c:516:43: warning: missing field 'dialog' initializer [-Wmissing-field-initializers]
NotificationAppletDialog dialog = {NULL, }; /* <- ? */
^
```
> Fix build warnings about missing field initializer

- configure.ac
- data/Makefile.am
- data/mate-notification-daemon.desktop.in.in
- data/org.freedesktop.mate.Notifications.service.in
- src/daemon/daemon.c
- src/daemon/daemon.h
- src/daemon/mnd-daemon.c
This is a proof-of-concept rework of an very old PR from 2013.
https://github.com/mate-desktop/mate-notification-daemon/pull/10
It removes dbus-activation for notification-daemon and the daemon will start via autostart folder in x11 and wayland session.
Relying on D-Bus activation to launch org.freedesktop.Notifications can result in a race condition if multiple daemons are present on one computer, as explained further in the commit messages.
For example, GNOME 2.x vs KDE:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=584859
https://bugs.kde.org/show_bug.cgi?id=212656
And KDE vs. Unity (notify-osd):
http://ubuntuforums.org/showthread.php?t=1973315
These are just examples. The general problem is discussed further here:
https://bugzilla.redhat.com/show_bug.cgi?id=484945
We have several …
> auto-start m-n-d with session 

- configure.ac
- data/Makefile.am
- data/org.mate.applets.MateNotificationApplet.desktop.in.in
- src/capplet/Makefile.am
- src/capplet/mate-notification-applet.c
Allow building the do not disturb panel applet in-process, it can then be used in wayland
> Wayland: Allow building do not disturb applet in process

- src/daemon/daemon.c
Fix
https://github.com/mate-desktop/mate-notification-daemon/issues/216
> wayland: do not attempt to connect to x11 screensaver

- src/capplet/mate-notification-applet.c
Prevent the applet from breaking mate-panel's own translations, and make the applet actually use its translations (which it ironically didn't do, which meant it broke mate-panel's ones for nothing at all)
> applet: Fix i18n

- src/themes/coco/coco-theme.c
- src/themes/nodoka/nodoka-theme.c
- src/themes/slider/theme.c
- src/themes/standard/theme.c
```
coco-theme.c: In function 'set_notification_text':
coco-theme.c:509:9: error: implicit declaration of function 'xmlInitParser' [-Werror=implicit-function-declaration]
509 |         xmlInitParser();
|         ^~~~~~~~~~~~~
coco-theme.c:513:15: error: implicit declaration of function 'xmlReadMemory'; did you mean 'xmlInitMemory'? [-Werror=implicit-function-declaration]
513 |         doc = xmlReadMemory(str, (int) str_len, "noname.xml", NULL, 0);
|               ^~~~~~~~~~~~~
|               xmlInitMemory
coco-theme.c:513:13: warning: assignment to 'xmlDocPtr' {aka 'struct _xmlDoc *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
513 |         doc = xmlReadMemory(str, (int) str_len, "noname.xml", NULL, 0);
|             ^
coco-theme.c:561:9: error: implicit …
```
> fix building with libxml 2.12.0

- src/daemon/wayland.c
When using with Sway my notifications stopped appearing. It turns out this was because I had something like
```
output * pos 1600 1440
```
in my Sway config, and the original Wayland port I did didn't account for offset outputs.  This fixes that bug.
> Fix positioning on Wayland when output is not at position 0, 0

- src/daemon/daemon.c
- src/daemon/stack.c
- src/daemon/stack.h
May fix #218, or part of it.
Beware the I didn't test this myself, but @joakim-tjernlund did.  We need more testing, and see whether this effectively fixes the issues as reproduced by @raveit65 and @lukefromdc, as the fix here is related to monitors changing, while their reproducers might not have been.
The fix here is for properly updating the list of available monitors when that set changes. Before this patch, only the last monitor(s) would be removed, rather than the one(s) that got removed, which should cause issues if the primary monitor is removed, or more generally if any but the last is removed. While having this issue unnoticed could be a bit surprising, I suppose it is fairly unusual to disconnect the primary monitor, and was fairly unusual as well to have more than 2.
> daemon: Properly update the set of monitors when it changes

- src/daemon/daemon.c
remove exit / replace with gtk_main_quit
mate-notification daemon randomly crashes with Ubuntu noble. The daemon should shut down using gtk_main_quit rather than using exit(0);
[ 7590.265881] mate-notificati[76519]: segfault at 55ac5111c67a ip 00007d1d4fc09d61 sp 00007ffd0bf06698 error 4 in libgobject-2.0.so.0.8000.0[7d1d4fbdc000+37000] likely on  CPU 0 (core 0, socket 0)
[ 7590.265910] Code: 01 00 00 00 4c 89 ce 48 89 e5 e8 da e6 ff ff 5d 85 c0 0f 95 c0 0f b6 c0 c3 f3 0f 1e fa 48 85 ff 74 47 48 8b 07 48 85 c0 74 3f <48> 8b 00 48 3d fc 03 00 00 77 2c 48 8d 15 cd 53 02 00 48 c1 e8 02
> fix random crash of mate-notification-daemon

- src/themes/coco/coco-theme.c
- src/themes/nodoka/nodoka-theme.c
- src/themes/slider/theme.c
- src/themes/standard/theme.c
This is the patch to fix #222.
before:
after:
so, now we can:
```css
.notification-box { border:1px solid orange; background:cyan; }
.notification-box.coco-theme { background:yellow; }
.notification-box .countdown { }
.notification-box .actions-box { border:1px solid black; background-color:white; }
```
> Add classes for themes

- src/capplet/mate-notification-properties.c
- src/themes/coco/coco-theme.c
- src/themes/nodoka/nodoka-theme.c
- src/themes/slider/theme.c
- src/themes/standard/theme.c
After PR #232, this PR fix the background color of the countdown.
Made with the help of ChatGPT... but it's not a good dev!
**UPDATED**
without css:
with css:
```css
.notification-box .countdown:selected {
background-color: yellow;
}
```
- default color for coco countdown updated
- you can set countdown color for all themes
- countdown for slider theme is restored
- added timeout and button for preview notification
Without this PR and without CSS, for slider and default themes, the color of the countdown come from CSS theme: `:selected { background-color:gray; }`, for nodoka and coco themes, the color is hard-coded.
> Update countdown colors for coco theme

- data/org.mate.NotificationDaemon.gschema.xml.in
- src/capplet/mate-notification-properties.c
- src/capplet/mate-notification-properties.ui
- src/common/constants.h
- src/daemon/daemon.c
- src/daemon/daemon.h
- src/themes/coco/coco-theme.c
- src/themes/nodoka/nodoka-theme.c
- src/themes/slider/theme.c
- src/themes/standard/theme.c
This implements the [latest freedesktop notification spec](https://specifications.freedesktop.org/notification-spec/latest-single/), specifically:
- allow notifications to persist (resident vs transient)
- provide app icons from their desktop-entry
I also added a few extra features:
- configurable default timeout
- display countdown on all notifications (instead of only those expecting user input)
- expose all those settings in the capplet
Fixes #132 
Fixes #137 
Fixes #138 
Fixes #149
> implement Desktop Notification Specification v1.3

- configure.ac
- src/daemon/daemon.c
Recent versions of libwnck introduced a WnckHandler object to be used as the main entry point into the library.
> daemon: Bump libwnck to 43.0
